### ISSUE TITLE
Scope: Organization doesn't seem to work

### ISSUE THREAD

**Issue by jgwinner** [roncsak/getRunnerToken#56]
I tried doing a simple YAML with a PAT token that has Admin:Org scope:

Input:
```
    - name: Get token for self-hosted runner registration
      uses: roncsak/getRunnerToken@v1.0.0
      id: runner_registration
      with:
         scope: "organization"
         token: ${{ secrets.PAT_RUNNER_TOKEN }}
```

I tried it with and without quotes, and even tried our specific organization. 

I get the following error in the GitHub Action log: `Error: Invalid scope organization! err2`

Full log:

```
Run roncsak/getRunnerToken@v1.0.0
  with:
    scope: organization
    token: ***
  env:
    AWS_DEFAULT_REGION: us-west-2
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
(node:1672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Invalid scope organization! err2
Error: HttpError: Not Found err2
```

Any ideas?
